### ISSUE TITLE
Error after installing this package.

### ISSUE THREAD

**Issue by ashique12009** [s-sarthak/laravel-multiauth#21]
![route-error](https://user-images.githubusercontent.com/5427021/44948258-4d1fca80-ae3c-11e8-8731-913b93182613.png)
I think it is route error.
Also after installing this package by composer command, i see it it on require object in composer.json file.
Hope you can get what's going on.

**Comment by ashique12009** [comment]
I have ran below both command but no luck. Same result.
1. composer dump-autoload 
2. php artisan route:clear

**Comment by s-sarthak** [comment]
Upload your project somewhere so that I can assist you

**Comment by s-sarthak** [comment]
Hey, unfortunately, this package is not compatible with laravel 5.4 yet and your project is on 5.4, 

Now I am working on it to make it work on 5.4 also, and when I did that I will inform you.
I am not closing this issue until I solve your issue.
Thanks

**Comment by ashique12009** [comment]
then for which version of laravel i should use for this package?
Thanks

**Comment by s-sarthak** [comment]
You can use it for 5.6 and 5.7

**Comment by s-sarthak** [comment]
Hey fixed it, for 5.4 you can download this package via composer require bitfumes/laravel-multiauth:5.4.x-dev
